version: '3.8'

services:
  postgres:
    container_name: postgres
    build: 'environment/postgres'
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      monitoring:
        aliases:
          - postgres
  best-shop-ever:
    container_name: best-shop-ever
    build: 'best-shop-ever'
    ports:
      - 8080:8080
    networks:
      monitoring:
        aliases:
          - best-shop-ever
    depends_on:
      - postgres
  grafana:
    container_name: grafana
    build: 'environment/grafana'
    user: "$UID:$GID"
    ports:
      - 3000:3000
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
    depends_on:
      - prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    user: "$UID:$GID"
    ports:
      - 9090:9090
    volumes:
      - ./environment/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./volumes/prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
    depends_on:
      - best-shop-ever

networks:
  monitoring: