[package]
name = "openapi"
version = "1.0.0"
authors = ["OpenAPI Generator team and contributors"]
edition = "2018"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "^2.2"
futures = "0.3.19"
actix-web = "3.3.3"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
rust_decimal = { version = "1.19.0", features = ["db-tokio-postgres"] }
rust_decimal_macros = "1.19.0"
[dependencies.reqwest]
version = "^0.11"
features = ["json", "multipart"]

[dev-dependencies]

[features]
